### ISSUE TITLE
Nothing is shown in output

### ISSUE THREAD

**Issue by andresriancho** [prevade/cloudjack#3]
```
[eth:~/tools/cloudjack] master(+109/-99)* ± python cloudjack.py 

  oooooooo8 o888                              oooo ooooo                      oooo        
o888     88  888   ooooooo  oooo  oooo   ooooo888   888   ooooooo    ooooooo   888  ooooo 
888          888 888     888 888   888 888    888   888   ooooo888 888     888 888o888    
888o     oo  888 888     888 888   888 888    888   888 888    888 888         8888 88o   
 888oooo88  o888o  88ooo88    888o88 8o  88ooo888o  888  88ooo88 8o  88ooo888 o888o o888o 
						 8o888
			CloudJack v1.0.2

[eth:~/tools/cloudjack] master(+109/-99)*
```

I know I have the AWS credentials properly configured, and I know that the organization I'm connecting to has cloudfront / route53.

The tool should at least show something like: "Analyzing instance X", "X is not vulnerable because ..."

**Comment by bryanmcaninch** [comment]
@andresriancho do you have the required IAM permissions as noted in #3 and #4 of the README file?

**Comment by andresriancho** [comment]
I'm 99% sure I have the permissions, even if I wouldn't , the tool should output **something** letting me know that I don't.

**Comment by bryanmcaninch** [comment]
@andresriancho I created an IAM test user called "cloudjack" with no permissions. Created a "cloudjack" profile in ~/.aws/credentials with the cloudjack user's access key ID and secret access key. I receive the following error when I run the cloudjack.py script using the cloudjack profile:

```
[user][~/github/cloudjack] ./cloudjack.py -p cloudjack

  oooooooo8 o888                              oooo ooooo                      oooo
o888     88  888   ooooooo  oooo  oooo   ooooo888   888   ooooooo    ooooooo   888  ooooo
888          888 888     888 888   888 888    888   888   ooooo888 888     888 888o888
888o     oo  888 888     888 888   888 888    888   888 888    888 888         8888 88o
 888oooo88  o888o  88ooo88    888o88 8o  88ooo888o  888  88ooo88 8o  88ooo888 o888o o888o
						 8o888
			CloudJack v1.0.2

Traceback (most recent call last):
  File "./cloudjack.py", line 180, in <module>
    main()
  File "./cloudjack.py", line 91, in main
    for hosted_zone in sorted(route53.list_hosted_zones()['HostedZones']):
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListHostedZones operation: User: arn:aws:iam::935044474330:user/cloudjack is not authorized to perform: route53:ListHostedZones
[user][~/github/cloudjack]
```

**Comment by andresriancho** [comment]
Good. I have the permissions, still... it would be ideal for the tool to show **something** when run. For example: `Did X, and found nothing interesting`, `No Route53 configurations found in this AWS organization`, etc.

**Comment by bryanmcaninch** [comment]
Added verbosity flag.

**Comment by andresriancho** [comment]
Thanks!
